items = {
    "Infinity Edge": {"Attack Damage": 80, "Crit Chance": 25, "Crit Multiplier": 0.4},
    "Wild Arrows": {"Attack Damage": 65, "Crit Chance": 25, "Crit Multiplier": 0.35},
    "Bloodthirster": {"Attack Damage": 80, "Lifesteal": 18},
    "Blade of the Ruined King": {"Attack Damage": 50, "Attack Speed": 0.25, "Current Health Damage": 6},
    "Statikk Shiv": {"Attack Damage": 55, "Attack Speed": 0.45, "Crit Chance": 0},
    "Phantom Dancer": {"Attack Damage": 0, "Attack Speed": 0.6, "Crit Chance": 25},
    # "Rapid Firecannon": {"Attack Damage": 0, "Attack Speed": 0.35, "Crit Chance": 25},
    "The Collector": {"Attack Damage": 60, "Crit Chance": 25, "Lethality": 12},
    "Kraken Slayer": {"Attack Damage": 50, "Attack Speed": 0.40},
    "Essence Reaver": {"Attack Damage": 70, "Crit Chance": 25, "Mana Regen": 1.5},
    "Lord Dominik's Regards": {"Attack Damage": 45, "Crit Chance": 25, "Percent Armor Penetration": 35},
    # "Mortal Reminder": {"Attack Damage": 35, "Crit Chance": 25, "Grievous Wounds": 0.3, "Percent Armor Penetration": 35},
    # "Hurricane": {"Attack Damage": 0, "Attack Speed": 0.4, "Crit Chance": 0},
    "Wit's End": {"Attack Damage": 0, "Attack Speed": 0.55, "Magic Resist": 40},
    # "Serpent's Fang": {"Attack Damage": 55, "Lethality": 15},
    # "Umbral Glaive": {"Attack Damage": 50, "Lethality": 15},
    "Youmuu's Ghostblade": {"Attack Damage": 60, "Lethality": 18},
    # "Edge of Night": {"Attack Damage": 50, "Lethality": 15},
    "Axiom Arc": {"Attack Damage": 55, "Lethality": 18},
    "Oppertunity": {"Attack Damage": 55, "Lethality": 18},
    "Volt": {"Attack Damage": 55, "Lethality": 18},
    "Hubris": {"Attack Damage": 60, "Lethality": 18},
    "Profane Hydra": {"Attack Damage": 60, "Lethality": 18},
    "Serylda Grudge": {"Attack Damage": 45, "Crit Chance": 0, "Percent Armor Penetration": 0, "Lethality": 15},
    "Guinsoos Rageblade": {"Attack Damage": 35, "Attack Speed": 0.25, "Ability Power": 35, "On Hit": 30},
    "Trinity Force": {"Attack Damage": 45, "Attack Speed": 0.33, "Ability Power": 35, "Spell Blade": 2, "Health": 300},
    "Rav": {"Attack Damage": 70, "Ability Haste": 20},
    "Titanic": {"Attack Damage": 50, "Health Scaling On Hit": 0.015, "Health": 550},
    "Hullbreaker": {"Attack Damage": 65, "Health Scaling On Hit": 0.035, "Base Attack Damage Scaling": 4, "Health": 500},
    "OverLords BloodMail": {"Attack Damage": 40, "Health Scaling On Hit": 0.035, "Base Attack Damage Scaling": 4, "Health": 500},

}